services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./stock-search-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
