name: Build and Push Docker Images

on:
  push:
    branches:
      - main # Triggers on commits to the main branch. Modify this if needed.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx (for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # Dockerfile for backend in the root directory
          push: true
          tags: |
            sprx7767/ind_portfolio_optimization-backend:latest
            sprx7767/ind_portfolio_optimization-backend:${{ github.sha }}

      # Step 5: Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./stock-search-app # Path to frontend directory
          file: ./stock-search-app/Dockerfile # Dockerfile for frontend
          push: true
          tags: |
            sprx7767/ind_portfolio_optimization-frontend:latest
            sprx7767/ind_portfolio_optimization-frontend:${{ github.sha }}
